# Generated by Django 4.2.1 on 2024-04-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'system_intent',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('fkintent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatBot.intent')),
            ],
            options={
                'db_table': 'system_response',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('fkintent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatBot.intent')),
            ],
            options={
                'db_table': 'system_pattern',
            },
        ),
    ]
