# Generated by Django 4.2.1 on 2024-04-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatBot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageInitial', models.CharField(max_length=100)),
                ('epoch', models.IntegerField()),
                ('batchsize', models.IntegerField()),
            ],
            options={
                'db_table': 'system_setting',
            },
        ),
    ]
